name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4 # v2.0.1
        with:
          tofu_version: "1.12.2"

      - name: tofu fmt
        run: tofu fmt -check -recursive

      - name: tofu init
        run: tofu init -backend=false

      - name: tofu validate
        run: tofu validate

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2

      - name: tflint
        run: tflint
